services:
  postgres:
    image: postgres:15-alpine
    container_name: tx-processor-postgres
    environment:
      POSTGRES_DB: tx_processor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tx_processor"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tx-processor-network

  redis:
    image: redis:7-alpine
    container_name: tx-processor-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - tx-processor-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tx-processor-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - tx-processor-network
    profiles:
      - tools

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tx-processor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - tx-processor-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  tx-processor-network:
    driver: bridge
